### PR TITLE
Bump to 0.10.3

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge/tokenizers any idea about this OSX CI issue at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=367600&view=logs&jobId=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445?

```
  915 | / map_impl! {
  916 | |     [true P1],
  917 | |     [true P1 P2],
  918 | |     [true P1 P2 P3],
  ...   |
  921 | |     [false P1 P2 P3 P4 P5 P6],
  922 | | }
      | |_- in this macro invocation
      |
     ::: /Users/runner/miniforge3/conda-bld/tokenizers_1629891064352/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.15.3/src/data_traits.rs:452:18
      |
  452 |   pub unsafe trait DataOwned: Data {
      |                    --------- required by a bound in this
  ...
  455 |           + RawDataSubst<Self::Elem, Output=Self>;
      |             ------------------------------------- required by this bound in `data_traits::DataOwned`
      |
      = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to 208 previous errors

  For more information about this error, try `rustc --explain E0277`.
  error: could not compile `ndarray`.

  Caused by:
    process didn't exit successfully: `rustc --crate-name ndarray --edition=2018 /Users/runner/miniforge3/conda-bld/tokenizers_1629891064352/_build_env/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.15.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembed-bitcode=no --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=590ba65c2147b948 -C extra-filename=-590ba65c2147b948 --out-dir /private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps --target x86_64-apple-darwin -C linker=x86_64-apple-darwin13.4.0-clang -L dependency=/private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps -L dependency=/private/tmp/pip-req-build-anus8zny/target/release/deps --extern matrixmultiply=/private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps/libmatrixmultiply-4bd86281cefe6307.rmeta --extern num_complex=/private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps/libnum_complex-32fea16c76bc69b3.rmeta --extern num_integer=/private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps/libnum_integer-5194b620af335fc4.rmeta --extern num_traits=/private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps/libnum_traits-54bbdfbdace1d108.rmeta --extern rawpointer=/private/tmp/pip-req-build-anus8zny/target/x86_64-apple-darwin/release/deps/librawpointer-6666f5dc7bdb7702.rmeta --cap-lints allow -C 'link-args=-Wl,-install_name,@rpath/tokenizers.cpython-38-darwin.so'` (exit code: 1)
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  error: cargo failed with code: 101

  Building wheel for tokenizers (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "$PREFIX/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "$PREFIX/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
    raise InstallationError(
```

**Comment by hadim** [comment]
From @xhochy on conda-forge chat:

> One difference with osx-64 is that we have the rust version still pinned to 1.46 whereas all other platforms (incl. osx-arm64) use a newer rust version

@conda-forge/tokenizers How do you feel about merging this without osx-64 support and we can address it once a newer version of rust is available for osx-64?

Looks like we'll have to wait for rust 1.55 for osx-64 support. See https://github.com/conda-forge/rust-feedstock/issues/73 for details.

**Comment by hadim** [comment]
1.55 has been released from https://github.com/conda-forge/rust-feedstock/issues/73#issuecomment-917415302

I trigger a new build.

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
@conda-forge/tokenizers LGTM

**Comment by setu4993** [comment]
Thanks @hadim! Reviewing now.

**Review by setu4993 — APPROVED** [review]

**Pull request merged**
