### PR TITLE
Bump build number and re-render to compile for Python 3.10.

### PR DESCRIPTION
**Pull request by corajr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by corajr** [comment]
@conda-forge-admin please rerender

**Comment by corajr** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
There was quite a lot of work towards this in #40, but I've been waiting for a long time for upstream to finally release a version based on this...

**Comment by h-vetinari** [comment]
Obsoleted by #53

**Pull request closed without merging**
