### PR TITLE
Rebuild for python310 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Continues from #39 

Closes #49

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/rust
I don't know why `PYO3_CROSS_PYTHON_VERSION` does not seem to take effect here. I'm following the same approach as [`cryptography`](https://github.com/conda-forge/cryptography-feedstock/blob/main/recipe/meta.yaml), where this doesn't run into the problem below:
```
  error: failed to run custom build command for `pyo3 v0.12.4`

  Caused by:
    process didn't exit successfully: `/home/conda/feedstock_root/build_artifacts/tokenizers_1647840012296/work/target/release/build/pyo3-e872c55050f3b1f9/build-script-build` (exit status: 1)
    --- stderr
    Error: "Python 3 required version is 3.5, current version is 3.1"
```

**Comment by isuruf** [comment]
See https://github.com/conda-forge/cryptography-feedstock/pull/81#issuecomment-960517781

**Comment by h-vetinari** [comment]
> See [conda-forge/cryptography-feedstock#81 (comment)](https://github.com/conda-forge/cryptography-feedstock/pull/81#issuecomment-960517781)

Ah, I had forgotten about that - many thanks! Weird that they're so far behind with pyo3. Patching it is then...

**Comment by h-vetinari** [comment]
Yay, a fixture that enforces running from a specific directory... 
```
    @pytest.fixture(scope="session")
    def data_dir():
>       assert os.getcwd().endswith("python")
E       AssertionError
```

**Comment by h-vetinari** [comment]
aarch + 3.10 is blocked on https://github.com/conda-forge/multiprocess-feedstock/pull/37 (due to test dep).

**Comment by h-vetinari** [comment]
Woohoo, a test suite that runs through in emulation 🥳
(still with 1 failure that's still being investigated in https://github.com/huggingface/tokenizers/pull/956, but an much better than failing at import already)

**Comment by h-vetinari** [comment]
OK, we're down to: 
* https://github.com/huggingface/tokenizers/issues/957 for python 3.10 everywhere
* remaining type error being worked on in https://github.com/huggingface/tokenizers/pull/956
* new error on windows, apparently due to https://github.com/conda-forge/multiprocess-feedstock/pull/37:
  ```
    File "C:\Miniconda\lib\site-packages\conda\exports.py", line 236, in <listcomp>
      actions['LINK'] = [index[d] for d in actions['LINK']]
  KeyError: Dist(channel='conda-forge', dist_name='multiprocess-0.70.12.2-py37hcc03f2d_2', name='multiprocess', fmt='.tar.bz2', version='0.70.12.2', build_string='py37hcc03f2d_2', build_number=2, base_url=None, platform=None)
  ```
* An encoding error on windows (currently hidden by the previous error):
  ```
  input = array([['My', 'name', 'is', 'John'],
         ['My', 'name', 'is', 'Georges']], dtype='<U7')
  is_pretokenized = True
       def test_single(input, is_pretokenized=False):
          output = tokenizer.encode_batch(input, is_pretokenized=is_pretokenized)
  >       assert format(output) == result_single
  E       AssertionError: assert [['[CLS]', 'm..., '##r', ...]] == [['[CLS]', 'm...es', '[SEP]']]
  E         At index 1 diff: ['[CLS]', 'my', 'name', 'is', 'geo', '##r', '[SEP]'] != ['[CLS]', 'my', 'name', 'is', 'georges', '[SEP]']
  E         Use -v to get more diff

  tests\bindings\test_tokenizer.py:177: AssertionError
  ```

**Comment by h-vetinari** [comment]
So this is going to need a bunch of upstream work that's now been done but not merged yet. I'm not comfortable in backporting that, so I proposed to wait for the new release that's [planned](https://github.com/huggingface/tokenizers/pull/956#issuecomment-1076109687) in the next 1-3 weeks or so.

**Comment by h-vetinari** [comment]
Fun... Running more extensive tests now runs into the missing cryptography builds for openssl3 through requests->urllib3->cryptography...

**Comment by h-vetinari** [comment]
OK, aside from openssl 3 problems, tentatively trying to backport https://github.com/huggingface/tokenizers/pull/956 to 0.12.1 (now applies essentially without conflicts) runs into some more cross-compilation issues:
```
    --- stderr
    error: The `auto-initialize` feature is enabled, but your python installation only supports embedding the Python interpreter statically. If you are attempting to run tests, or a binary which is okay to link dynamically, install a Python distribution which ships with the Python shared library.

    Embedding the Python interpreter statically does not yet have first-class support in PyO3. If you are sure you intend to do this, disable the `auto-initialize` feature.

    For more information, see https://pyo3.rs/v0.16.2/building_and_distribution.html#embedding-python-in-rust
```

I'm trying to follow what the cryptography feedstock is [doing](https://github.com/conda-forge/cryptography-feedstock/blob/main/recipe/meta.yaml), but it obviously doesn't seem to be working... The link above to the pyo3 docs also doesn't get me much further.

Tips welcome.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge/rust 
The build instructions here had [worked](https://github.com/conda-forge/tokenizers-feedstock/pull/40#issuecomment-1073817751) earlier this year, but now there's widespread fall-out in all cross-compilation jobs. Anything that changed in the setup, or is there something obvious I'm missing here?

**Comment by h-vetinari** [comment]
Funnily enough this sorted itself out in #53 🤷 🙃

**Pull request closed without merging**
