### PR TITLE
Enable win

### PR DESCRIPTION
**Pull request by oblute**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oblute** [comment]
Has something changed in that in the last few months? Previously, the compiler wouldn't work, but `libgcc-ng` in run did.

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by oblute** [comment]
@chrisburr it's just confusing because this build went fine back at the end of july: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=186639&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0

**Comment by chrisburr** [comment]
The issue is the version of rust specified in `conda_build_config.yaml`. As that is only available from `defaults`:
```
Loading channels: done
# Name                       Version           Build  Channel
rust_linux-64                 1.29.0      he6710b0_0  pkgs/main
rust_linux-64                 1.38.0      he6710b0_1  pkgs/main
rust_linux-64                 1.40.0      he6710b0_1  pkgs/main
rust_linux-64                 1.46.0      h49f0194_0  conda-forge
rust_linux-64                 1.46.0      he6710b0_0  pkgs/main
rust_linux-64                 1.46.0      hf484d3e_0  pkgs/main
```
it's "impossible" to install now that strict channel priority is enabled by default (basically, if a package exists in a channel none of the lower priority channels will be used for it). I don't remember when this was enabled but I think it was relatively recent.

```bash
$ mamba create --override-channels -c conda-forge/label/rust_dev -c conda-forge --strict-channel-priority  --name test rust_linux-64=1.29.0 gcc_linux-64=7

Looking for: ['rust_linux-64=1.29.0', 'gcc_linux-64=7']

Encountered problems while solving.
Problem: nothing provides requested rust_linux-64 1.29.0**
```

Can you remove the rust lines from `conda_build_config.yaml` and rerender?

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/840 should fix it

**Comment by oblute** [comment]
@chrisburr that didn't quite succeed :(

**Comment by isuruf** [comment]
Need https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/840 as well.

**Comment by oblute** [comment]
@isuruf what are we waiting on to get https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/840 merged?

**Comment by oblute** [comment]
@chrisburr @isuruf should i be removing the config file entirely? it's not even registering rust as a package to be installed at the start of the build.

**Comment by chrisburr** [comment]
You should definitely revert b5c3eef. The issue now is with the repodata conda uses, I'll get back to you shortly...

**Comment by chrisburr** [comment]
@conda-forge/core, any ideas why `mamba` can solve this but conda can't?

```bash
$ conda create --override-channels -c conda-forge/label/rust_dev -c conda-forge --strict-channel-priority  --name test rust_linux-64 gcc_linux-64=7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package gcc_linux-64 conflicts for:
rust_linux-64 -> rust=1.46.0 -> gcc_linux-64=7
rust_linux-64 -> gcc_linux-64
gcc_linux-64=7
Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by isuruf** [comment]
Because `rust_linux-64` is not in `conda-forge/label/rust_dev` and `rust` is. Try removing `conda-forge/label/rust_dev`. (Also PRs welcome to add `rust_linux-64` to `rust_dev`)

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by oblute** [comment]
@isuruf @chrisburr any idea why this is now failing on unix but passing on windows?

**Comment by Anthchirp** [comment]
I believe I've got this to work in #8

**Pull request closed without merging**
