### PR TITLE
compile for different openssl versions

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #46.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
I can't find documentation that says this package depends on openssl, but searching the repo you find that when they build their software, they consider installing openssl-devel through yum

https://github.com/huggingface/tokenizers/search?q=openssl&type=

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
I would confirm with upstream what you need here. It seems that openssl is useful in OSX as well but you might need to specify flags manually.
https://github.com/huggingface/tokenizers/blob/28cd3dce2a75d106572392194ff2564574c33235/bindings/python/tokenizers_manual_m1_build.sh

**Review by setu4993 — APPROVED** [review]
Thanks for the quick help here, @hmaarrfk! Appreciate it.

I'm going to get this out, try to get the `transformers` package updated and then figure out what (if anything) is required for MacOS (https://github.com/conda-forge/tokenizers-feedstock/pull/47#issuecomment-1133662593).

**Pull request merged**
