### PR TITLE
update to v0.9.3 and add Windows builds

### PR DESCRIPTION
**Pull request by Anthchirp**
Following advice in conda-forge/conda-forge-pinning-feedstock#875

closes #3
closes #4
closes #6
closes #7
closes #9

added myself as maintainer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge/tokenizers builds pass, so this is ready to review/merge

I am not a rust/setuptools-rust expert, but here is what I found on the linux/macos builds: Right now these are only passing because the `CARGO_BUILD_TARGET` environment variable is unset via a build script. The variable is normally set by default (eg. to `x86_64-unknown-linux-gnu` for linux builds), which causes the individual rustc commands to run with an `--out-dir /tmp/pip-req-build-(..)/target/x86_64-unknown-linux-gnu/release/deps` parameter. This changes where the `.so`/`dylib` files go. `setuptools-rust` however does not realise that this is the case, [likely a known, but undocumented problem](https://github.com/PyO3/setuptools-rust/blob/75fa9ab31351071a490b8d9c18826adf05ceb047/setuptools_rust/build.py#L96-L101), leading to a crash along the lines of
```
      Finished release [optimized] target(s) in 5m 46s
  error: rust build failed; unable to find any *tokenizers.so in /tmp/pip-req-build-g1y7sip7/target/release
  Building wheel for tokenizers (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for tokenizers
```
I expect this would affect every conda-forge package building on setuptools-rust 🤔. Something we maybe should report upstream.

Since I fixedthe immediate issue here by unsetting the build target this should work, but it will likely also break any cross-compiling attempts while the fix is in place.

**Review by setu4993 — APPROVED** [review]
Thanks, @Anthchirp, this makes sense to me, but I'm also not 100% on if this is the _best_ workaround.

I'm okay with merging it for now, but would like to wait for another reviewer who is more familiar with the Rust build system to review and confirm.

**Comment by oblute** [comment]
thanks @Anthchirp for the unix workaround, but i'm not a rust expert either and i am a bit cautious about the solution. i'm okay with merging for now as well, but before i'm just pinging @conda-forge/core @conda-forge/rust does anyone have any insight on the fix made to unset `CARGO_BUILD_TARGET` and the issues with `setuptools-rust`?

**Comment by isuruf** [comment]
How about patching our `setuptools-rust` package by adding something like,
```
if 'CARGO_BUILD_TARGET' in os.environ:
  target_args = ["--target", os.environ["CARGO_BUILD_TARGET"]]
```
at https://github.com/PyO3/setuptools-rust/blob/75fa9ab31351071a490b8d9c18826adf05ceb047/setuptools_rust/build.py#L102

**Comment by Anthchirp** [comment]
That wouldn't solve the issue, as that would only instruct `setuptools-rust` to drop the files there, but it still wouldn't look for the results in that place. I've adapted your suggestion though so that `setuptools-rust` should look in the other place, and passed it upstream in the ☝️ linked PR

**Comment by Anthchirp** [comment]
upstream has already merged the PR. I've put in a PR for a backported patched version at conda-forge/setuptools-rust-feedstock#8

**Comment by Anthchirp** [comment]
@conda-forge-admin please rerender

**Comment by Anthchirp** [comment]
With `setuptools-rust` fixed I've removed the workaround and this is now ready to be merged @conda-forge/tokenizers

**Pull request merged**
